#!/usr/bin/env sh

# TODO: uncomment after seeder libs created

migrate() {
  nx build api-database-migrations && \
    env-cmd -f .env.local node dist/libs/api/database/migrations/src/index.js $1
}

migrate_seed() {
  nx build api-cli-seed && \
    env-cmd -f .env.local node dist/apps/api/cli/seed/main.js
}

migrate_ci() {
  nx build api-database-migrations && \
    node dist/libs/api/database/migrations/src/index.js $1
}

migrate_ci_seed() {
  nx build api-cli-seed && \
    node dist/apps/api/cli/seed/main.js
}

case $1 in
  'create')
    touch libs/api/database/migrations/src/migrations/$(date '+%Y%m%d%H%M%S')_$2.ts
    ;;
  'ci')
    case $2 in
      'latest')
        migrate_ci $2
        ;;
      'rollback')
        migrate_ci $2
        ;;
      'seed')
        migrate_ci_seed
        ;;
    esac
    ;;
  'latest')
    migrate $1
    ;;
  'rollback')
    migrate $1
    ;;
  'seed')
    migrate_seed
    ;;
  'refresh')
    migrate rollback && migrate latest && migrate_seed
    ;;
  *)
    echo "Usage: $0 { create table_name | latest | rollback | seed | refresh }"
    ;;
esac
